### ISSUE TITLE
引入重启就报错了

### ISSUE THREAD

**Issue by oday-xiexin** [pig-mesh/excel-spring-boot-starter#13]
Description:
Parameter 0 of constructor in com.pig4cloud.plugin.excel.ResponseExcelAutoConfiguration required a single bean, but 2 were found:
 - requestMappingHandlerAdapter: defined by method 'requestMappingHandlerAdapter' in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]
 - repositoryExporterHandlerAdapter: defined by method 'repositoryExporterHandlerAdapter' in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class]

**Comment by oday-xiexin** [comment]
spring boot是 2.2.5.RELEASE, spring-cloud.version是Hoxton.RELEASE

**Comment by lltx** [comment]
尝试一下 0.0.9   兼容多个 MappingHandlerAdapter d的情况
