### ISSUE TITLE
导出没有过滤不展示的字段

### ISSUE THREAD

**Issue by 863416870** [pig-mesh/excel-spring-boot-starter#17]

**Comment by ChunMengLu** [comment]
@ExcelIgnore  注解不生效？

**Comment by 863416870** [comment]
抱歉我沒有描述清楚，字段用属性用 exclude 来排除过滤的未生效
![image](https://user-images.githubusercontent.com/43089579/116339809-ad937f80-a810-11eb-8eb5-a8273c7f5d1d.png)
![image](https://user-images.githubusercontent.com/43089579/116339837-bb490500-a810-11eb-9164-b4974e1627ed.png)

**Comment by ChunMengLu** [comment]
> 抱歉我沒有描述清楚，字段用属性用 exclude 来排除过滤的未生效
> ![image](https://user-images.githubusercontent.com/43089579/116339809-ad937f80-a810-11eb-8eb5-a8273c7f5d1d.png)
> ![image](https://user-images.githubusercontent.com/43089579/116339837-bb490500-a810-11eb-9164-b4974e1627ed.png)

转接给 @lltx  了，已经通知他来确认处理

**Comment by lltx** [comment]
https://github.com/pig-mesh/excel-spring-boot-starter/blob/227907850af3b2a23eaff1c7b031d45cc7ba2061/src/main/java/com/pig4cloud/plugin/excel/handler/AbstractSheetWriteHandler.java#L86


看起来是这里的BUG

-  已fix 你可以使用 0.4.1 版本
-  或者使用 @ExcelIgnore 标识字段
