### ISSUE TITLE
功能需求：数据字典映射功能

### ISSUE THREAD

**Issue by ITCodd** [pig-mesh/excel-spring-boot-starter#41]
如：status：1：启用，0：禁用
1：下载模板时，根据数据字典的标签生成下拉，启用，禁用
2：上传时，根据字符串，映射成数字1,0
希望能提供一个字典的处理接口

**Comment by kangaroo1122** [comment]
自定义转换就搞定吧

**Comment by ITCodd** [comment]
也行，能有easypoi那样便捷的功能更好
