### ISSUE TITLE
Long[] 类型数据导出报错

### ISSUE THREAD

**Issue by qiaoqiao888** [pig-mesh/excel-spring-boot-starter#7]
版本：0.0.5
![image](https://user-images.githubusercontent.com/18333714/93440935-34d75700-f902-11ea-8de8-5d9d1bc81278.png)

**Comment by lltx** [comment]
只能是基本数据类型， 要放到cell 里面的 数组无法放啊

**Comment by ChunMengLu** [comment]
🤪内置处理一下，冷神
